version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229

    command: bash -c "npx prisma migrate resolve --applied 20240705065628_init && npm run start:dev"
    depends_on:
      - postgres
    restart: no

  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
